### ISSUE TITLE
Is there an alternative for React Native?

### ISSUE THREAD

**Issue by lluisandreu** [pusher/pusher-websocket-react-native#101]
Hello! 
This library keeps crashing using a presence channel on iOS. 
The last crash from Crashlytics is telling me that: **Unhandled JS Exception: TypeError: Cannot read property 'members' of undefined, js engine: hermes**. caused by the onAuthorize function after a previous error digesting HASH.

These errors does not happen in Android.

I would like to know if there is another library supporting Pusher and React Native out there. Perhaps Pusher JS?
Many thanks.

**Comment by raphaeldcout** [comment]
+1

**Comment by lluisandreu** [comment]
Finally I installed Pusher JS and it works much better and no errors.

**Comment by raphadcout** [comment]
wow, that's good. The official docs recommend "pusher-websocket-react-native" on README. How do you install Pusher JS?

**Comment by lluisandreu** [comment]
@raphadcout just use the JS repo: https://github.com/pusher/pusher-js and import it.

import Pusher from 'pusher-js';

Remember to unsubscribe o disconnect when the app goes on background or out of focus.

**Comment by benjamin-tang-pusher** [comment]
You may need into install netinfo as well.

`npm install --save @react-native-community/netinfo`

The error message from metro can be cryptic, but this fixed a similar looking dependency issue for me.

**Comment by benjamin-tang-pusher** [comment]
Closing this issue, let us know if installing the above doesn't fix your dependency issue.
