### ISSUE TITLE
RTCCallableJSModules is not set error

### ISSUE THREAD

**Issue by Bayramito** [pusher/pusher-websocket-react-native#105]
Still getting this error randomly when i trigger an event
![Ekran Resmi 2023-07-20 13 37 46](https://github.com/pusher/pusher-websocket-react-native/assets/44513402/e7f5d80e-ab84-4063-9925-7aab7901bda8)

**Comment by fbenevides** [comment]
I'll close this issue as it's duplicated. (#85)
