### ISSUE TITLE
How to use this library in an Expo Managed Project

### ISSUE THREAD

**Issue by Jake-Mulhern** [pusher/pusher-websocket-react-native#108]
I am currently attempting to implement Pusher in an Expo managed React-Native project but get an error stating that this library cannot be used in Expo.

```
ERROR  Error: The package 'pusher-websocket-react-native' doesn't seem to be linked. Make sure: 

- You have run 'pod install'
- You rebuilt the app after installing the package
- You are not using Expo managed workflow
```

Is there any way around this?

**Comment by kauan777** [comment]
I have the same problem, how i fix it?

**Comment by nandorojo** [comment]
You'd need to use an expo custom dev client.

**Comment by keshav263** [comment]
Hi @nandorojo . It still doesn't work for me. Can you please help me with the steps you took to achieve it? As soon as I try to subscribe to an event using pusher, I get the same error "not linked"

**Comment by nandorojo** [comment]
```
npx expo prebuild 
npx expo run:ios -d
```

Please look up custom development clients on the expo docs.

**Comment by benjamin-tang-pusher** [comment]
As already mentioned by [nandorojo](https://github.com/nandorojo), please examine the expo prebuild documentation https://docs.expo.dev/workflow/prebuild/ 

You have to run `npx expo prebuild` after you've installed this library in order to generate the android and ios folders (like a standard React Native project) then `run npx expo run:android` to start it.

I will close this issue shortly unless you have other issues.

**Comment by keshav263** [comment]
Yes, thank you for the response. What worked for me was to create a development build using EAS. Looked like a lot less trouble. https://docs.expo.dev/develop/development-builds/create-a-build/

**Comment by eylonshm7** [comment]
@keshav263 Created an Expo developmentBuild, but still get the 'doesn't seem to be linked' error, wondering what else did you do?

**Comment by eylonshm7** [comment]
@benjamin-tang-pusher Tried to use both development build and `expo run:ios`, keep getting the same 'doesn't seem to be linked', do you know what could be the problem?
