### ISSUE TITLE
Idea: use a sync API

### ISSUE THREAD

**Issue by nandorojo** [pusher/pusher-websocket-react-native#114]
I think initializing Pusher / connecting to channels / binding events should be sync functions. The fact that they return promises makes it harder to deal with them in useEffect. It also increases the odds of memory leaks. This is apparent by the fact that the example app doesn't even start listening in an effect, but rather on a button press, which real apps don't do. I assume this would require setting up sync connections to the native functions.

Alternatively, adding some React hooks that handle this setup for you could be a nice DX boost.

**Comment by Jonatthu** [comment]
Not only that, but this API does not match the pusher-js API interface and makes it hard to work with react-native-web, I have to do all that manual work. When building universal apps.

**Comment by nandorojo** [comment]
Yeah it makes it hard to use with Solito. I’m using custom `.native.tsx` files in my own app.

**Comment by Jonatthu** [comment]
I even had to wrote my own hooks and providers 🤦🏽‍♂️
<img width="320" alt="image" src="https://github.com/pusher/pusher-websocket-react-native/assets/3742176/dfe21b49-e7f2-4bee-adaf-304c1d8d69ce">
