### ISSUE TITLE
pusher is not linking in react-native library when library is getting used by some projects 

### ISSUE THREAD

**Issue by can2112** [pusher/pusher-websocket-react-native#117]
we have created one simple react-native library which is under the hood using the @pusher-websocket-react-native,

**Comment by can2112** [comment]
I have cross verified that pusher is in the node modules but it is not getting linked automatically

**Comment by benw-pusher** [comment]
You will need to run the steps at https://docs.expo.dev/workflow/customizing/#adding-custom-native-code-with-development-builds. See #108 for more info on this.

**Comment by NDKhanh96** [comment]
I am built development build in eas and it worked: https://docs.expo.dev/develop/development-builds/create-a-build/
