### ISSUE TITLE
Expo managed react native app

### ISSUE THREAD

**Issue by tuanthanh2067** [pusher/pusher-websocket-react-native#122]
Hello everyone, 

I couldn't find this information anywhere else, I think it's maybe not available but I'm looking for a way to use Pusher in my expo managed react native app. When I try to install it with `npm install @pusher/pusher-websocket-react-native`, and run the app, I got an error related to `pod install`. I tried to run it, and got a different error saying `no `podfile' found in the project directory`

![image](https://github.com/pusher/pusher-websocket-react-native/assets/51014333/531b672a-1251-473b-99d9-863cef0fca72)

**Comment by tuanthanh2067** [comment]
@benw-pusher 

Oh, this is an expo managed react native app, so there's no ios directory. 

![image](https://github.com/pusher/pusher-websocket-react-native/assets/51014333/fd28d6e6-f358-42c0-9454-566e73dbdaa2)

**Comment by benw-pusher** [comment]
Apologies, your screenshot with the complete error message didn't load when I last commented. 

To solve the 'this package doesn't seem to be linked' error you need to follow the build instructions at https://docs.expo.dev/workflow/customizing/#adding-custom-native-code-with-development-builds. See https://github.com/pusher/pusher-websocket-react-native/issues/108 for more info on this.

**Comment by boredland** [comment]
hey @benw-pusher! I couldn't figure out how to do that, based on those links. As react-native recommends using expo in their "getting started" guide, wouldn't it be a good idea to offer a basic guide as to set up expo with pusher? I'd really love to keep using pusher, but this is blocking me out completely.
