### ISSUE TITLE
Pusher Beams React Native

### ISSUE THREAD

**Issue by ChampiMagic** [pusher/pusher-websocket-react-native#128]
## Problem:
We need to add Pusher Beams service to our application created in react native to send notifications when the application is idle.

## Question:
Does this SDK allow the use of Pusher Beams or just Channels (from what I have seen, it would be the second option). If not, is there any "official" react native SDK to use Pusher Beams? Or do you have any recommendation on how to implement it (besides the native method)?

**Comment by yashmaurya321-crypto** [comment]
To add Pusher Beams service to your React Native application, you can use the React Native Pusher Beams SDK. [This SDK is not officially supported by Pusher, but it is built by a member of the Pusher Beams Developer Community and is available on GitHub ](https://github.com/redantnl/react-native-beams-wrapper)[1](https://github.com/redantnl/react-native-beams-wrapper).

You can also use the Pusher Channels SDK to send notifications, but it is a different service than Pusher Beams (https://pusher.com/docs/beams/reference/all-libraries/)[2](https://pusher.com/docs/beams/reference/all-libraries/).

If you prefer to use Pusher Beams, you can use the Pusher Beams Web SDK to integrate Pusher Beams with your React Native application (https://pusher.com/docs/beams/getting-started/web/sdk-integration/)[3](https://pusher.com/docs/beams/getting-started/web/sdk-integration/).

Alternatively, you can use the React Native Beams Wrapper to add Pusher Beams to your React Native application. [This is a third-party library that wraps the Pusher Beams SDK and provides a simple interface for React Native developers ](https://github.com/redantnl/react-native-beams-wrapper)[1](https://github.com/redantnl/react-native-beams-wrapper).
