### ISSUE TITLE
Failed to resolve: com.pusher:pusher-java-client:2.+

### ISSUE THREAD

**Issue by jorgefl0** [pusher/pusher-websocket-react-native#134]
I'm having an issue building Android distributions. The Maven artifacts are not able to be found for some reason. 

The weird thing is that we do see the Maven packages here https://mvnrepository.com/artifact/com.pusher/pusher-java-client

Any idea how to resolve it? 

This is the dependency declaration that seems to be the issue.

**_https://github.com/pusher/pusher-websocket-react-native/blob/067f8ff1133c780aedb257659f62d569eaf0c2b7/android/build.gradle#L126_**

**Comment by benw-pusher** [comment]
@jorgefl0 are you still encountering this issue? This could have been a temp issue with Maven - I am able to build without error here.

**Comment by jorgefl0** [comment]
@benw-pusher Thanks for checking in. I'm not sure what the root cause, but I ended up resetting our native app template. This resolved my issue. Thanks for the support.
