### ISSUE TITLE
Forced Closing on when opening app on React Native Ios.

### ISSUE THREAD

**Issue by billoneillighttiger** [pusher/pusher-websocket-react-native#148]
After I add the package and when initializing the pusher(pusher.init()) with config on ios17, then app is closed.
React Native version is 0.72.7.
Once I remove the pusher.init method, the app works well. Of course, the app works without Pusher feature.

**Comment by benw-pusher** [comment]
Can you share any error messages or logs that you have from the crash?

**Comment by billoneillighttiger** [comment]
Oops, sorry, I found the cause that I have entered app id (integer) into the apiKey(string) of pusher.init. 
I have found that from Xcode debug. Thanks.
