### ISSUE TITLE
Installation guide for Expo

### ISSUE THREAD

**Issue by masudhossain** [pusher/pusher-websocket-react-native#150]
Documentation mentions nothing about Expo. Was previously using pusher-js perfectly fine, but cannot anymore.

**Comment by benw-pusher** [comment]
You need to follow the build instructions provided by Expo at https://docs.expo.dev/workflow/customizing/#adding-custom-native-code-with-development-builds. See https://github.com/pusher/pusher-websocket-react-native/issues/108 for more info on this.
