### ISSUE TITLE
Allow subscribing to specific channel event

### ISSUE THREAD

**Issue by amitava82** [pusher/pusher-websocket-react-native#155]
In web client `bind` method allows subscribing to specific event which isn't possible here. Also there is no way to add event listeners after channel has been subscribed. This makes impossible to subscribe to a channel events later point of time.

I'm proposing 2 changes:
1. Add `bind` like functionality so that my component can listen to events it is interested in.
2. Allow adding event listeners after channel has been subscribed so that components can subscribe to events when it is mounted.

**Comment by benw-pusher** [comment]
Thanks for the feedback - we aren't able to commit to a release for this at this time
