### ISSUE TITLE
Expo pusher podFile

### ISSUE THREAD

**Issue by eylonshm7** [pusher/pusher-websocket-react-native#159]
As it seems in the readme, `pusher-websocket-swift` pod should be added.
"The Pusher Channels React Native plugin adds the pusher-websocket-swift cocoapod to your project".

I'm running `expo prebuild`, `expo run:ios`, `pod install` etc.., but even tho the package is in my package.json, yarn.lock etc, it's not gets added to the podfile, which means I can't use the package with Expo, maybe there's a bug which should be fixed? 

 Anyway, even if I install `pusher-websocket-swift` pod manually, I keep getting the same error: `"The package 'pusher-websocket-react-native' doesn't seem to be linked"`

**Comment by ekpono** [comment]
I am having the same issue with Expo

I keep getting `The package 'pusher-websocket-react-native' doesn't seem to be linked`

"react-native": "0.74.5",
 "expo": "~51.0.28",
 "@pusher/pusher-websocket-react-native": "^1.3.1",
 
 Although I have not ran `pod install` but it doesnt even work on my android simulator.
 
 
 Any solution to this?

**Comment by christaiwo** [comment]
> I am having the same issue with Expo
> 
> I keep getting `The package 'pusher-websocket-react-native' doesn't seem to be linked`
> 
> "react-native": "0.74.5", "expo": "~51.0.28", "@pusher/pusher-websocket-react-native": "^1.3.1",
> 
> Although I have not ran `pod install` but it doesnt even work on my android simulator.
> 
> Any solution to this?

I'm facing the same issue now, were you able to find a work around?

**Comment by ekpono** [comment]
> > I am having the same issue with Expo
> > I keep getting `The package 'pusher-websocket-react-native' doesn't seem to be linked`
> > "react-native": "0.74.5", "expo": "~51.0.28", "@pusher/pusher-websocket-react-native": "^1.3.1",
> > Although I have not ran `pod install` but it doesnt even work on my android simulator.
> > Any solution to this?
> 
> I'm facing the same issue now, were you able to find a work around?

From your root directory run `npx pod-install`

**Comment by christaiwo** [comment]
> > > I am having the same issue with Expo
> > > I keep getting `The package 'pusher-websocket-react-native' doesn't seem to be linked`
> > > "react-native": "0.74.5", "expo": "~51.0.28", "@pusher/pusher-websocket-react-native": "^1.3.1",
> > > Although I have not ran `pod install` but it doesnt even work on my android simulator.
> > > Any solution to this?
> > 
> > 
> > I'm facing the same issue now, were you able to find a work around?
> 
> From your root directory run `npx pod-install`

So my issue now is, I'm building an android app and not ios.

`Warning: Error: The package 'pusher-websocket-react-native' doesn't seem to be linked. Make sure:

- You rebuilt the app after installing the package
- You are not using Expo managed workflow`

**Comment by ekpono** [comment]
> > > > I am having the same issue with Expo
> > > > I keep getting `The package 'pusher-websocket-react-native' doesn't seem to be linked`
> > > > "react-native": "0.74.5", "expo": "~51.0.28", "@pusher/pusher-websocket-react-native": "^1.3.1",
> > > > Although I have not ran `pod install` but it doesnt even work on my android simulator.
> > > > Any solution to this?
> > > 
> > > 
> > > I'm facing the same issue now, were you able to find a work around?
> > 
> > 
> > From your root directory run `npx pod-install`
> 
> So my issue now is, I'm building an android app and not ios.
> 
> `Warning: Error: The package 'pusher-websocket-react-native' doesn't seem to be linked. Make sure:
> 
> * You rebuilt the app after installing the package
> * You are not using Expo managed workflow`

If it is android run `npx expo run:android`
make sure you are not using Expo Go, use the development build

**Comment by christaiwo** [comment]
> > > > > I am having the same issue with Expo
> > > > > I keep getting `The package 'pusher-websocket-react-native' doesn't seem to be linked`
> > > > > "react-native": "0.74.5", "expo": "~51.0.28", "@pusher/pusher-websocket-react-native": "^1.3.1",
> > > > > Although I have not ran `pod install` but it doesnt even work on my android simulator.
> > > > > Any solution to this?
> > > > 
> > > > 
> > > > I'm facing the same issue now, were you able to find a work around?
> > > 
> > > 
> > > From your root directory run `npx pod-install`
> > 
> > 
> > So my issue now is, I'm building an android app and not ios.
> > `Warning: Error: The package 'pusher-websocket-react-native' doesn't seem to be linked. Make sure:
> > 
> > * You rebuilt the app after installing the package
> > * You are not using Expo managed workflow`
> 
> If it is android run `npx expo run:android` make sure you are not using Expo Go, use the development build

Thanks for this, it's working fine now.

**Comment by aonemd** [comment]
Hey, I created a new expo app and installed `@pusher/pusher-websocket-react-native` to test the issue. 

It seems to be running out of the box; I didn't need to do something special. For example:
- for iOS: I could run `npx pod-install` and `npx expo run:ios` to run the ios app.
- for Android: `npx expo run:android`.

I'll consider this ticket resolved and close it for now. Thanks everyone.
