### ISSUE TITLE
Android build is failing all of the sudden

### ISSUE THREAD

**Issue by Shasikhan** [pusher/pusher-websocket-react-native#168]
Before builds were not having any issue. Today I tried to build release APK and getting following error:

Could not determine the dependencies of task ':app:lintVitalReportRelease'.
> Could not resolve all task dependencies for configuration ':app:releaseRuntimeClasspath'.
   > Could not resolve com.pusher:pusher-java-client:2.+.
     Required by:
         project :app > project :pusher_pusher-websocket-react-native
      > Failed to list versions for com.pusher:pusher-java-client.
         > Unable to load Maven meta-data from https://oss.sonatype.org/content/repositories/snapshots/com/pusher/pusher-java-client/maven-metadata.xml.
            > Could not HEAD 'https://oss.sonatype.org/content/repositories/snapshots/com/pusher/pusher-java-client/maven-metadata.xml'. Received status code 504 from server: Gateway Time-out

**Comment by aonemd** [comment]
Hey @Shasikhan it seems like there's a major outage in Maven Central https://status.maven.org/

**Comment by Shasikhan** [comment]
@aonemd Thanks for quick reply. Now we have to wait? or there is anything we can do temporarily?

**Comment by Shasikhan** [comment]
Now outage is over and its working as expected.
