### ISSUE TITLE
error in download the library

### ISSUE THREAD

**Issue by karimsaad687** [pusher/pusher-websocket-react-native#170]
the library was working fine until today
<img width="1038" alt="Screenshot 2024-12-19 at 4 01 15 AM" src="https://github.com/user-attachments/assets/b959f2fc-6189-4489-ad54-a39cfa4a2560" />

**Comment by aonemd** [comment]
Hey @karimsaad687 , is this still a problem for you? I just tested with the [example app](https://github.com/pusher/pusher-websocket-react-native/tree/master/example) in this repo and it seems to be working fine. I remember recently there was an outage in some of the Maven repositories.
