### ISSUE TITLE
Connect to a different host

### ISSUE THREAD

**Issue by jasperjorna** [pusher/pusher-websocket-react-native#26]
Hi there,

Is is possible to connect to a server other than Pusher? So is it possible to pass along something like `host: '127.0.0.1:6001`?

**Comment by benw-pusher** [comment]
Hi, 

This library is designed for connecting the Pusher Channels only, it is not possible to connect to other hosts. 

Ben

**Comment by HaidarZ** [comment]
@jasperjorna  have you found a solution?

**Comment by themaxsmith** [comment]
https://github.com/pusher/pusher-websocket-react-native/pull/100

**Comment by hichemfantar** [comment]
@benw-pusher the pusher-js package supports it, any plans to add this?

**Comment by benw-pusher** [comment]
We don't have any current plans to add this.

**Comment by hichemfantar** [comment]
I managed to make it work with a fork, android works but not IOS
