### ISSUE TITLE
`pod install` fails

### ISSUE THREAD

**Issue by maxcan** [pusher/pusher-websocket-react-native#27]
On a bare react native (not expo) project.  Happens on v1.0.1 and v1.0.2

[!] CocoaPods could not find compatible versions for pod "pusher-websocket-react-native":
  In Podfile:
    pusher-websocket-react-native (from `../node_modules/@pusher/pusher-websocket-react-native`)

Specs satisfying the `pusher-websocket-react-native (from `../node_modules/@pusher/pusher-websocket-react-native`)` dependency were found, but they required a higher minimum deployment target.

**Comment by YosefOberlander** [comment]
I was able to fix this by changing my platform :ios in my pod file. I am on react-native version 0.69.2

**Comment by maxcan** [comment]
@YosefOberlander Thanks! Can I asked what you changed it to?  Mine is set to 12.4 on RN 0.69.3

**Comment by YosefOberlander** [comment]
@maxcan I changed mine to 14.5

**Comment by benw-pusher** [comment]
This library required `ios` deployment target of 13 or greater, was your version below this previously? 

In any case, I will close this as you have been able to resolve.

**Comment by maxcan** [comment]
@benw-pusher seems reasonable.  Mine was on 12.4.  I'll try moving to 13 soon and will let you know.  Currently using the pure JS library as a fallback
