### ISSUE TITLE
Cant pod install

### ISSUE THREAD

**Issue by nguyenngockha2904** [pusher/pusher-websocket-react-native#31]
React Native Version: 0.68.2
pusher-websocket-react-native version: 1.0.2.
Bare react-native project

<img width="667" alt="image" src="https://user-images.githubusercontent.com/55082300/188935134-f79b1440-6b56-4869-a94b-0ef93188deb4.png">
First, I install with platform: ios 12
<img width="1357" alt="image" src="https://user-images.githubusercontent.com/55082300/188935317-6a3905e4-7b7c-4b5b-aaf0-04487c06faea.png">

I think the reason is my platform is not higher minimum deployment target
so I change platform 12 => 13.0 like your example
but I cant pod install 
<img width="1379" alt="image" src="https://user-images.githubusercontent.com/55082300/188935954-681e2f13-5af0-4e2a-8e74-d473e8a024ef.png">

I have tried many ways, but it cant.
Does anyone have the same issue? please give me your solution, thanks

**Comment by benw-pusher** [comment]
You may need to open the xcworkspace file and ensure the minimum targets are set correctly there as well, then try pod install once more.
