### ISSUE TITLE
Random Crash Fatal Exception: java.lang.UnsupportedOperationException: JsonObject

### ISSUE THREAD

**Issue by sarthakpranesh** [pusher/pusher-websocket-react-native#33]
**What is seen in app**
During development itself app would start and immediately crash. This is not always the behavior, at times app would start and then later randomly crash again. On looking more closely with Android Studio's logcat we are able to find the same error as listed on Firebase Crashlytics. The most weird thing is, this crash is only noticed in the application from around 8.30am morning to 7.00pm in evening.

Our use case involves using Channels to pass events from a backend to mobile application. It'll be of great help if someone can point towards a solution or possible causes triggering such an issue.

**Can we share code-base**
Unfortunately not

**Exception**
```
Fatal Exception: java.lang.UnsupportedOperationException: JsonObject
       at com.google.gson.JsonElement.getAsString(JsonElement.java:179)
       at com.pusher.client.channel.PusherEvent.fromJson(PusherEvent.java:88)
       at com.pusher.client.connection.websocket.WebSocketConnection.lambda$onMessage$5$WebSocketConnection(WebSocketConnection.java:212)
       at com.pusher.client.connection.websocket.-$$Lambda$WebSocketConnection$LH620kMWP6e8WFdl-2ZQYqgldrg.run(:4)
       at com.pusher.client.util.Factory.lambda$queueOnEventThread$0(Factory.java:140)
       at com.pusher.client.util.-$$Lambda$Factory$zJWSbSBBJ9pXjI_LpAkJ-3_Kedw.run(:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:920)
```

**Comment by sarthakpranesh** [comment]
On looking into the issue a bit more yesterday, I found the error was more prominent on version of this lib that were using the latest pusher-java-client 2.4.1-2 (in build gradle you'll find pusher-java-client:2.+ or something like that).

For our use case we were only using public channels not private channels but this issue still surfaced. So we removed the React Native lib and moved to pusher-java-client 2.2.1 and worked with bridge to create connections and subscriptions to channels. It has been working since yesterday, I am not sure if strictly defining pusher-java-client 2.2.1 in this lib's gradle using patch-package can help fix this issue but worth a try.

**Comment by proggen-com** [comment]
This is an issue in the 2.4.1 version of the java lib, we're working on a fix

**Comment by benjamin-tang-pusher** [comment]
pusher-websocket-java 2.4.1 was release about a month ago, are any of you still getting the error?

**Comment by sarthakpranesh** [comment]
I have not tried 2.4.1 again @benjamin-tang-pusher 
We have shifted to this https://github.com/pusher/pusher-websocket-react-native/issues/33#issuecomment-1253188988

**Comment by benjamin-tang-pusher** [comment]
@barsumek How about you? I've tried repeating your steps but mine is able to connect to a private channel. The build.gradle in node_modules/pusher-websocket-react-native will get api `com.pusher:pusher-java-client:2.+` which should resolve to the latest 2.4.2.

**Comment by benjamin-tang-pusher** [comment]
Due to lack of response, and the changes 2.4.2 version of [pusher-websocket-java](https://github.com/pusher/pusher-websocket-java) that likely fixed this, I'm going to close this thread.
