### ISSUE TITLE
issue when used in expo environment 

### ISSUE THREAD

**Issue by Dhananjay-JSR** [pusher/pusher-websocket-react-native#38]
![image](https://user-images.githubusercontent.com/47073516/193680082-9c52f38f-739d-4ddd-a125-ccaeb4b11a46.png)

**Comment by Dhananjay-JSR** [comment]
![image](https://user-images.githubusercontent.com/47073516/193687809-5db89ef7-cbee-439d-abd3-8d82e96ce6c7.png)

more issue when tried ejecting app with prebuild

**Comment by benw-pusher** [comment]
Can you try and run with the info or debug flags mentioned in your second error so we can see more detail?

**Comment by benw-pusher** [comment]
We haven't received a response here so I'll close this off. If you need further assistance please reach out via support at https://support.pusher.com/hc/en-us/requests/new

**Comment by Abhijeet1828** [comment]
I am facing the exact same issue as well.
