### ISSUE TITLE
Cannot Dynamically change `authEndpoint` after init

### ISSUE THREAD

**Issue by khopkins218** [pusher/pusher-websocket-react-native#41]
Problem:
We have users who have multiple identities in our systems - when they logout and sign in under a new identity, they are unable to authenticate against private channels because the necessary URLs we use for authing users are dynamic to the user. When calling `Pusher.getInstance()` it returns the previously invoked instance stopping us from disconnecting & destroying the previous pusher instance and invoking a new one to init with the new `authEndpoint`

on iOS, it appears to work by just setting:

```
const pusher = Pusher.getInstance();
pusher.authEndpoint = '' // new endpoint
``` 

but when doing that on android, it crashes the app with `IllegalStateException` and message `Cannot subscribe to a private or presence channel because no ChannelAuthorizer has been set. Call PusherOptions.setChannelAuthorizer() before connecting to Pusher`.

**Comment by benjamin-tang-pusher** [comment]
Hi, we don't have plans to officially support changing the auth endpoint after init, but we are hoping to implement changing the header and auth params after init, which we've done in pusher-js 7.6.0 and will eventually roll out to the other libraries. I will add this as a feature request to our Android and iOS libraries (which our RN library uses).

**Comment by khopkins218** [comment]
thanks @benjamin-tang-pusher. I ended up swapping us over to pusher-js specifically for this capability. We appreciate your work!
