### ISSUE TITLE
Getting an error

### ISSUE THREAD

**Issue by avijit-ordering** [pusher/pusher-websocket-react-native#49]
Hello, I am getting this error. 

D:\app\app\orderingapp2\android\app\build\generated\rncli\src\main\java\com\facebook\react\PackageList.java:15: error: package com.pusherwebsocketreactnative does not exist
import com.pusherwebsocketreactnative.PusherWebsocketReactNativePackage;
                                     ^
D:\app\app\orderingapp2\android\app\build\generated\rncli\src\main\java\com\facebook\react\PackageList.java:121: error: cannot find symbol
      new PusherWebsocketReactNativePackage(),
symbol:   class PusherWebsocketReactNativePackage

I am using 
"@pusher/pusher-websocket-react-native": "^1.1.1"
"react-native": "^0.64.2"
OS: Windows 10
Platform: Android
Can you please let me know how I can solve it?

**Comment by proggen-com** [comment]
I'm not sure of react native 0.64 is supported, that's quite an old verion

**Comment by avijit-ordering** [comment]
Can you please let me know if there is any way to work pusher for this react native version?
Thanks

**Comment by benw-pusher** [comment]
Did manually linking the library help resolve this for you, @avijit-ordering ?

**Comment by benw-pusher** [comment]
Hi @tdammy92 - best to raise your own issue here. 

Closing this one as we haven't had a response since providing a solution at https://github.com/pusher/pusher-websocket-react-native/issues/49#issuecomment-1315700385

**Comment by avijit-ordering** [comment]
Hi @benw-pusher .
First, I am very sorry for the late response. As per your instruction, I have tried with manually linking (react-native link) but getting same issue still now.
Thanks.

**Comment by MursiDirect** [comment]
**Same issue here using exact the same environment** 
OS: Windows 10
Platform: Android

"react-native": "^0.64.2",
"@pusher/pusher-websocket-react-native": "^1.1.1",

Any solution yet, please?

**Comment by avijit-ordering** [comment]
@MursiDirect 
Please add the bellow into build.gradle
 classpath ('org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.10')
