### ISSUE TITLE
Support for newer authenticate vs authorize seems to be missing

### ISSUE THREAD

**Issue by akenger** [pusher/pusher-websocket-react-native#50]
The newer JS libraries support a "signin" method as documented by pusher to be the preferred way of handing authentication, then authorization is handled differently as well.  This library seems to only support the old single-srream authentication flow.  Is this accurate?  If so, why are we being told to use this react native library over the more mature JS library?  I'm quite confused.  Any guidance would be appreciated.

**Comment by LFMAKER** [comment]
Any updates on this issue? 
https://github.com/pusher/pusher-websocket-react-native/issues/40

We paid thousands of dollars to not have the basics in a lib.

**Comment by akenger** [comment]
FYI - I did some digging in the underlying swift lib and it's not supported there yet either so clearly that's why it's a  limitation of the RN lib

**Comment by frechg** [comment]
If I want to be able to send events to specific users, as described here in [Sending events to authenticated users](https://pusher.com/docs/channels/server_api/server-to-user-messages/), but that functionality is not included in the RN lib, what's an alternative strategy?

Should I subscribe each user to their own private channel that includes their user id (ie: private-user-10) so I have a way to send messages on a user by user basis? I'm not building a feed, but maybe the strategy for a typical social media feed update would work for my use case.

**Comment by benw-pusher** [comment]
Hi @frechg - that would be an appropriate workaround in the absence of the new users features. 
We will roll out the new users features over time.
