### ISSUE TITLE
Invalid key in subscription auth data

### ISSUE THREAD

**Issue by lionxcr** [pusher/pusher-websocket-react-native#52]
Hello team, we are trying to implement a react native pusher client for our existing infrastructure.

We are using `onAuthorizer` to manage our authentication flow, custom params...
- here we return our `secret:signature` from our custom authentication flow
- we are then returning the following object to our implementation:
`{
          auth: authResult.auth,
          channel_data: JSON.stringify({userId}),
        }`
- Subscription to private channel fails

yet we face an invalid key error referring to our secret chunk of the string as if it was trying to parse it as hash due to the `:` in the secret +  : + signature.

I am completely puzzled about this... please advice.

`Invalid key in subscription auth data: 'SECRET_HERE'

  | reactConsoleErrorHandler | @ | ExceptionsManager.js:149
-- | -- | -- | --
  | registerError | @ | LogBox.js:204
  | console.error | @ | LogBox.js:67
  | overrideMethod | @ | backend.js:2171
  | onError | @ | NotificationService.ts:25
  | (anonymous) | @ | index.tsx:158
  | emit | @ | _EventEmitter.js:149
  | __callFunction | @ | MessageQueue.js:419
  | (anonymous) | @ | MessageQueue.js:116
  | __guard | @ | MessageQueue.js:370
  | callFunctionReturnFlushedQueue | @ | MessageQueue.js:115
  | (anonymous) | @ | debuggerWorker.js:69
`

**Comment by akenger** [comment]
@lionxcr sounds like you're implementing the authentication in a weird way on the backend.  Are you using your own method to generate the responding auth token and payload or are you using one of the pusher implementations?  You should also be sending back the channel_data you get back from your endpoint, not reconstructing it and sending.  authResult should have channel_data.  You should be able to just return your whole authResult back to your implementation.

**Comment by benw-pusher** [comment]
Hi @lionxcr did you get anywhere with this following @akenger's advice?
