### ISSUE TITLE
Passing custom authentication header on authEndpoint

### ISSUE THREAD

**Issue by tdammy92** [pusher/pusher-websocket-react-native#53]
Please I need urgent help, my authorization endpoint, accept two param Auth, id.

how do i achieve this with this pusher-websocket-react-native package

**Comment by akenger** [comment]
See https://github.com/pusher/pusher-websocket-react-native/issues/40#issuecomment-1322408009

**Comment by tdammy92** [comment]
@akenger 🙏🙏  thanks a bunch, but i had to adjust my authendpoint to accept what is needed.
