### ISSUE TITLE
Undefined Symbol when building on IOS

### ISSUE THREAD

**Issue by chrizLopez** [pusher/pusher-websocket-react-native#58]
Help please. i'm having this error when building on IOS. 
I'm using the latest version of the sdk (v1.1.1)

<img width="878" alt="Screenshot 2022-11-29 at 9 10 46 PM" src="https://user-images.githubusercontent.com/32250278/204537698-1abafb2a-f0a1-40e2-907f-cf566a6667a1.png">

**Comment by Transmigrado** [comment]
I have the same problem, with version 1.1.1.

**Comment by chrizLopez** [comment]
@Transmigrado I fixed this issue by upgrading my react-native version from `0.64.4` to `0.67.2`. Hope this helps you as well.
