### ISSUE TITLE
[TypeError: f is not a function. (In 'f()', 'f' is undefined)]

### ISSUE THREAD

**Issue by seriklav** [pusher/pusher-websocket-react-native#59]
!Note:  use custom auth with Laravel back-end

When try connected to web socket with 
`await pusher.connect()`

got error on the console:
`[TypeError: f is not a function. (In 'f()', 'f' is undefined)]`

pls help who know how I can fixed crash my app )

**Comment by fbenevides** [comment]
hey @seriklav, I did the same steps as you said and I couldn't reproduce it. Are there any other steps?
