### ISSUE TITLE
App is crashed with next log

### ISSUE THREAD

**Issue by seriklav** [pusher/pusher-websocket-react-native#60]
![image](https://user-images.githubusercontent.com/5691789/205449493-6faa0bd8-24bb-46bd-bf9e-87ed7794756b.png)

**Comment by fbenevides** [comment]
Could you please elaborate a bit more on how to reproduce this? Thanks!

**Comment by benw-pusher** [comment]
We haven't received an instructions on how to reproduce this so we will close it. If you need further support please contact us at https://support.pusher.com/hc/en-us/requests/new
