### ISSUE TITLE
Pusher Authorization expecting wrong return

### ISSUE THREAD

**Issue by Vitor-Vilela** [pusher/pusher-websocket-react-native#61]
Hey guys, I'm having problems while using presence-channels, while on pusher-js the problems weren't happening, so, when I try subscribing to a presence-channel through my application the library seems to be expecting the wrong return from the backend side, according to this doc: https://pusher.com/docs/channels/library_auth_reference/auth-signatures/#worked-examples the auth route should return pusherKey: a hex digest of <socket_id>:<channel_name>:<JSON encoded user data>, and that's what we're doing on server side by using this method of pusher-http-go: 
![image](https://user-images.githubusercontent.com/98328435/205939162-6145b886-e862-40fd-a1e3-a4eefecaff98.png)
Where params is our socket_id and channel_name and memberData is our user data.
Here is the return of our authRoute, where the auth item is exactly what the doc tells and channel-data is the user info we used: 

`auth: ourPusherKey:76373596f2bba84a581abbc791d5461ac44ae979bceecf80c357e55372076412
channel_data: {"user_id":"9321318"}`

but the following error occurs, telling that pusher isn't expecting a hex digest of <socket_id>:<channel_name>:<user_data> as it should be, but it is expecting a hex digest of <socket_id>:<channel_name> without the user_data.

`Invalid signature: Expected HMAC SHA256 hex digest of 16085.17759627:presence-chat-app-D3C2DC7E-9553-46AC-B80E-6BD56C550E2F, but got 76373596f2bba84a581abbc791d5461ac44ae979bceecf80c357e55372076412`

This is our pusher init config:
![image](https://user-images.githubusercontent.com/98328435/205941022-40600bc5-07df-453e-ac87-2df45ba76e91.png)

Opening this issue since everything seems to be following what is recommended by the documentation, and the auth route worked with pusher-js. Also the error is not clear, since it seems to me it should not expect only socket_id:channel_name since it is a presence-channel.

(Did not include our key/route/headers to avoid security problems)

**Comment by johnsoncwb** [comment]
guys, this is a critical issue for our application

**Comment by herbertfuchs** [comment]
if you guys could take a look at it would be extremely helpful [🙏](https://emojipedia.org/folded-hands/)[🙏](https://emojipedia.org/folded-hands/)

**Comment by Vitor-Vilela** [comment]
Sorry guys, just realized by testing the return statement that it should also return the channel_data on the onAuthorizer function, the documentation for this method is kinda unclear but this solved the subscription issue!

**Comment by muzammil-kt** [comment]
@Vitor-Vilela can u share with me an example of how to return the data for the onAuthorizer function?
