### ISSUE TITLE
App closes without logs Android/IOS

### ISSUE THREAD

**Issue by tdammy92** [pusher/pusher-websocket-react-native#62]
i need help on my project. my app closes without any error.

but when i go into device logs/adb crash logs i get error from pusher.

**Version:
react-native: "0.69.7",
@pusher/pusher-websocket-react-native: ^1.1.1,**

example:IOS logs
`
Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Triggered by Thread:  0

Last Exception Backtrace:
0   CoreFoundation                	    0x7fff204055f4 __exceptionPreprocess + 226
1   libobjc.A.dylib               	    0x7fff201a4a45 objc_exception_throw + 48
2   Foundation                    	    0x7fff2075ea19 -[NSMutableDictionary(NSMutableDictionary) classForCoder] + 0
3   React                         	       0x108bd5d7a -[RCTEventEmitter sendEventWithName:body:] + 442 (RCTEventEmitter.m:50)
4   pusher_websocket_react_native 	       0x107b1c481 PusherWebsocketReactNative.callback(name:body:) + 273 (PusherWebsocketReactNative.swift:27)
5   pusher_websocket_react_native 	       0x107b20266 PusherWebsocketReactNative.changedConnectionState(from:to:) + 374 (PusherWebsocketReactNative.swift:119)
6   pusher_websocket_react_native 	       0x107b202bf @objc PusherWebsocketReactNative.changedConnectionState(from:to:) + 47
7   PusherSwift                   	       0x10768f92a partial apply + 26
8   PusherSwift                   	       0x10768ae96 PusherConnection.updateConnectionState(to:) + 390 (PusherConnection.swift:331)
9   PusherSwift                   	       0x10768b0e2 PusherConnection.resetConnection() + 178 (PusherConnection.swift:349)
10  PusherSwift                   	       0x10769913d PusherConnection.webSocketDidDisconnect(connection:closeCode:reason:) + 205 (PusherConnection+WebsocketDelegate.swift:53)
11  PusherSwift                   	       0x10769b429 protocol witness for WebSocketConnectionDelegate.webSocketDidDisconnect(connection:closeCode:reason:) in conformance PusherConnection + 9
12  NWWebSocket                   	       0x1070904d0 closure #1 in NWWebSocket.scheduleDisconnectionReporting(closeCode:reason:) + 288 (NWWebSocket.swift:318)
13  NWWebSocket                   	       0x107090518 thunk for @escaping @callee_guaranteed () -> () + 40
14  libdispatch.dylib             	    0x7fff201237f4 _dispatch_block_async_invoke2 + 83
15  libdispatch.dylib             	    0x7fff20115b25 _dispatch_client_callout + 8
16  libdispatch.dylib             	    0x7fff20123043 _dispatch_main_queue_drain + 1050
17  libdispatch.dylib             	    0x7fff20122c1b _dispatch_main_queue_callback_4CF + 31
`

**Comment by tdammy92** [comment]
> Could you please test it with the latest version? Thanks!

@fbenevides still the same, crashes persist.

**Comment by benw-pusher** [comment]
A support ticket is open for this. It appears the crash occurs when attempting to unsubscribe from a channel that the client was not subscribed to / when the client was not connected to Channels

**Comment by benw-pusher** [comment]
Closing this as we continue to progress the issue directly via support.
