### ISSUE TITLE
Crashes app when receiving an event ONLY if the remote JS debugger is on.

### ISSUE THREAD

**Issue by SavageWilliam** [pusher/pusher-websocket-react-native#66]
### My Setup
```
"@expo/react-native-action-sheet": "^4.0.1",
"expo": "^47.0.0",
```

I'm using `eas build` with development build. From my understanding the eas build runs `pod install` during that process. My app is not yet ejected. I'm running the build on a device as opposed to the simulator.

I've got everything set up and working, with the onEvent listener triggering correctly. 

### The Problem
However a new problem appeared - the app just crashes when receiving an event **when** the JS debugger is running. 

The crash happens even when no onEvent listener is defined.

EDIT: It also seems to happen sometimes when the debugger is closed 

Anyone else experiences this?

**Comment by Braden1996** [comment]
Sounds like this issue: https://github.com/pusher/pusher-websocket-react-native/issues/43

**Comment by fbenevides** [comment]
Could you please test it with the latest version? Thanks

**Comment by SavageWilliam** [comment]
Just upgraded to latest version and app crashing due to error 

`PusherReactNative:onConnectionStateChange is not a supported event type for PusherWebSocketReactNative.`

**Comment by benw-pusher** [comment]
Thanks @SavageWilliam . Is that a different error to the previous error you were encountering? 
 Are you able to share the code that triggers an error?

**Comment by benw-pusher** [comment]
We haven't had a response here so it is likely you have moved on - if that is not the case please let us know via https://support.pusher.com/hc/en-us/requests/new and we can progress with you.
