### ISSUE TITLE
CocoaPods could not find compatible versions for pod "pusher-websocket-react-native":

### ISSUE THREAD

**Issue by agunbuhori** [pusher/pusher-websocket-react-native#67]
I tried to install pusher by using command npx pod-install, I found this error.

**Comment by Pakile** [comment]
I have the same issue, @agunbuhori  you have any solutions?

**Comment by Pakile** [comment]
pusher-websocket-react-native require platform ios 13. check your Podfile `platform :ios, '13.0'`

**Comment by alokturkois** [comment]
@Pakile Thanks it worked for me when I change my platform : ios to 13

**Comment by trancongdung12** [comment]
nice 👌
