### ISSUE TITLE
Trigger event without authorization

### ISSUE THREAD

**Issue by gustavosantaella** [pusher/pusher-websocket-react-native#71]
I'm doing a application without backend. I want to send messages in real-time with pusher but i have the following error: **Trigger event is only for private/presence channels**
Is it possible to do tirgger event without authorization?

**Comment by fbenevides** [comment]
Hello @gustavosantaella,

No, it's not. Currently, Client Events require authorization, so they're just available on either private or presence channels. 

You can find more information about Client Events in the [Pusher Docs](https://pusher.com/docs/channels/using_channels/events/#triggering-client-events)
