### ISSUE TITLE
Undefined symbol _RCTEventEmitter

### ISSUE THREAD

**Issue by ricardoMogg** [pusher/pusher-websocket-react-native#78]
React Native version: 0.71.2
@pusher/pusher-websocket-react-native version: 1.2.1

I am currently seeing this error when building from XCode:
<img width="546" alt="Screenshot 2023-02-25 at 9 12 39 PM" src="https://user-images.githubusercontent.com/3887118/221393674-fc6c55ad-5cc8-448c-aba6-58f1e48109ea.png">

**Comment by ricardoMogg** [comment]
Proposing a PR that seems to fix this:

https://github.com/pusher/pusher-websocket-react-native/pull/77

**Comment by benw-pusher** [comment]
Can you update to the latest version and let me know if this helps? We recently released a round of bug fixes that should prevent this error.

**Comment by ricardoMogg** [comment]
thank you, we actually decided to change to a different library, I wish this was solved before.

**Comment by hichemfantar** [comment]
@ricardoMogg hey what library did you switch to?
