### ISSUE TITLE
Receiving data multiple times

### ISSUE THREAD

**Issue by AhmedHF** [pusher/pusher-websocket-react-native#80]
Listen to Multiple Events on a Pusher Channel 
like 
```
const createOrderChannel = async name => {
  await pusher.subscribe({
    channelName: name,
    onEvent: async event => {
      console.log(
        `################### Pusher ==> onEvent: ${
          JSON.parse(event.data).order
        }`,
      );
    },
  });
};
```

**Comment by benw-pusher** [comment]
Hi Ahmed, could you share more detail here? Are you expecting to receive the event once but are instead receiving it multiple times, or is it the opposite? What does your console.log output show?

**Comment by AhmedHF** [comment]
> console.log(
>         `################### Pusher ==> onEvent: ${
>           JSON.parse(event.data).order
>         }`,
>       );

console.log(
        `################### Pusher ==> onEvent: ${
          JSON.parse(event.data).order
        }`,
      );
     this appears 2 or 3 or more than once

**Comment by benw-pusher** [comment]
Do you see the event show multiple times in the [Pusher Debug console](https://pusher.com/docs/channels/getting_started/debugging/#viewing-application-events-in-the-channels-debug-console)?

**Comment by maxcheung1996** [comment]
so I am facing the exact same problem before on 1.2.2 when I try to init() every time on start a new connection and subscribe a channel, my solution is put the pusher.init() function into the root level of the app start such as app.js or index.js. It will ensure your init() function run only once to prevent such problem. Hope it would be help on your problem too!

This solution is credit by this user: https://github.com/pusher/pusher-websocket-react-native/issues/57#issuecomment-1331976776.

my sample code on app.js:

```
const initPusher = async () => {
  const pusher = Pusher.getInstance();

  const API_KEY = YOUR_ API_KEY;
  const API_CLUSTER = YOUR_ API_CLUSTER;

  await pusher.init({
    apiKey: API_KEY,
    cluster: API_CLUSTER,
  });
};

const App = () => {

  useEffect(() => {
    initPusher();
  }, []);

  return (
    <>
      ...rest of your code
    </>
  );
};
```

**Comment by benw-pusher** [comment]
Thanks for the suggested solution @maxcheung1996 

I'll close this out as we haven't had any more info from the original reporter. If you need any further support please reach out at https://support.pusher.com/hc/en-us/requests/new

**Comment by Subiyel** [comment]
> so I am facing the exact same problem before on 1.2.2 when I try to init() every time on start a new connection and subscribe a channel, my solution is put the pusher.init() function into the root level of the app start such as app.js or index.js. It will ensure your init() function run only once to prevent such problem. Hope it would be help on your problem too!
> 
> This solution is credit by this contributior: [#57 (comment)](https://github.com/pusher/pusher-websocket-react-native/issues/57#issuecomment-1331976776).
> 
> my sample code on app.js:
> 
> ```
> const initPusher = async () => {
>   const pusher = Pusher.getInstance();
> 
>   const API_KEY = YOUR_ API_KEY;
>   const API_CLUSTER = YOUR_ API_CLUSTER;
> 
>   await pusher.init({
>     apiKey: API_KEY,
>     cluster: API_CLUSTER,
>   });
> };
> 
> const App = () => {
> 
>   useEffect(() => {
>     initPusher();
>   }, []);
> 
>   return (
>     <>
>       ...rest of your code
>     </>
>   );
> };
> ```

Many Thanks @maxcheung1996  this works perfect. <3
