### ISSUE TITLE
Invalid signature: Expected HMAC SHA256 hex digest of

### ISSUE THREAD

**Issue by Bayramito** [pusher/pusher-websocket-react-native#84]
Sometimes i am getting this error, and the app immediately crashes.

Error Log:
```
Invalid signature: Expected HMAC SHA256 hex digest of 145814.20211781:presence-64347608ab76aa6d9f0da45a:{"user_id":1265}, but got f009e49f21a0e22213a9a26b03bed1544fea2883f3eb77c2f4898ca355ce5bd8 | 3 minutes ago at 08:14am
```

also getting this one too randomly

`Invalid key in subscription auth data: '<authorizer_timeout>'
`

<br class="Apple-interchange-newline">

**Comment by raphaeldcout** [comment]
+1

**Comment by benjamin-tang-pusher** [comment]
Did your app resume from background when this occurred? Could you also paste the rest of your errors here, in particular did you see a NullPointerError as well?

**Comment by benw-pusher** [comment]
We haven't had a response here so closing out.
