### ISSUE TITLE
Private Channel Subscription Error - IOS

### ISSUE THREAD

**Issue by hazhayder** [pusher/pusher-websocket-react-native#87]
Hi, 
We have been trying to implement pusher in `react-native 0.70.6` and using `"@pusher/pusher-websocket-react-native": "^1.2.1"` the problem that we are confronting that we are unable to subscribe we checked the `onAuthorizer` method and in the beginning of the method before writing any subscription we found that method is not being called. The application is running on a physical device on iOS 13 

Please help

**Comment by Asim313** [comment]
I'm facing same issue...

**Comment by Asim313** [comment]
> Can you share the code in use here?

import AsyncStorage from '@react-native-async-storage/async-storage';
import {Pusher} from '@pusher/pusher-websocket-react-native';
import API from '../../services/api/API';

export const connectEcho = async (fetchEcho, userId) => {

const pusher = Pusher.getInstance();

function onError(message, code, e) {
console.log(onError: $message code: ${code} exception: ${e});
}

function onConnectionStateChange(currentState, previousState) {
console.log(Connection: ${currentState});
}

function onMemberAdded(channelName, member) {
console.log(onMemberAdded: ${channelName} user: ${member});
}

function onMemberRemoved(channelName, member) {
console.log(onMemberRemoved: ${channelName} user: ${member});
}

async function onSubscriptionSucceeded(channelName, data) {
console.log(
onSubscriptionSucceeded: ${channelName} data: ${JSON.stringify(data)},
);
}

function onEvent(event) {
//console.log(Global_onEvent: ${event});
}

function onSubscriptionError(channelName, message, e) {
console.log(
onSubscriptionError: ${message} channelName: ${channelName} Exception: ${e},
);
}

function onDecryptionFailure(event, reason) {
console.log(onDecryptionFailure: ${event} reason: ${reason});
}

function onSubscriptionCount(subscriptionCount) {
console.log(onSubscriptionSucceeded: ${subscriptionCount});
}

try {
await pusher.init({
apiKey: '2e0caf8dcdc2-------',
cluster: 'ap2',
authEndpoint: 'https://enginear.exodevs.com/api/broadcasting/auth',
onAuthorizer: async (channelName, socketId) => {
console.log('Channel:', channelName, 'SocketId:', socketId);
const response = await API.postAuthData({
socket_id: socketId,
channel_name: channelName,
});
console.log("Response of auth:: ", response)
return {
auth: [response.data](http://response.data/).auth,
};
},
onConnectionStateChange,
onError,
onEvent,
onSubscriptionSucceeded,
onSubscriptionError,
onDecryptionFailure,
onMemberAdded,
onMemberRemoved,
onSubscriptionCount,
});

await pusher.connect();
await pusher.subscribe({
channelName: private-messenger.user.${userId},
onEvent: event => {
fetchEcho(event);
},
});
} catch (e) {
console.log(ERROR: ${e});
}
};

**Comment by benw-pusher** [comment]
Are you seeing requests to the authEndpoint or the API. postAuthData route? 
You are using both the authEndpoint and the onAuthorizer function - you do not need to specify the authEndpoint when using the onAuthorizer function. 

Do you see a connection to our service is correctly established?

**Comment by hazhayder** [comment]
> Are you seeing requests to the authEndpoint or the API. postAuthData route? You are using both the authEndpoint and the onAuthorizer function - you do not need to specify the authEndpoint when using the onAuthorizer function.
> 
> Do you see a connection to our service is correctly established?

Hi, 
We don’t see any request coming to auth endpoint moreover, we only find connecting state in pusher logs that’s it

**Comment by hazhayder** [comment]
How can I enable the log to debug console in Pusher please share the process.

**Comment by hazhayder** [comment]
@benw-pusher Could you please help here, we are on a short deadline here?

**Comment by benw-pusher** [comment]
There is logging in your code snippets already provided 
```
 function onError(message, code, e) {
    console.log(`onError: $message code: ${code} exception: ${e}`);
  }

  function onConnectionStateChange(currentState, previousState) {
    console.log(`Connection: ${currentState}`);
  }

  function onMemberAdded(channelName, member) {
    console.log(`onMemberAdded: ${channelName} user: ${member}`);
  }

  function onMemberRemoved(channelName, member) {
    console.log(`onMemberRemoved: ${channelName} user: ${member}`);
  }

  async function onSubscriptionSucceeded(channelName, data) {
    console.log(
      `onSubscriptionSucceeded: ${channelName} data: ${JSON.stringify(data)}`,
    );
  }

  function onEvent(event) {
    //console.log(`Global_onEvent: ${event}`);
  }

  function onSubscriptionError(channelName, message, e) {
    console.log(
      `onSubscriptionError: ${message} channelName: ${channelName} Exception: ${e}`,
    );
  }

  function onDecryptionFailure(event, reason) {
    console.log(`onDecryptionFailure: ${event} reason: ${reason}`);
  }

  function onSubscriptionCount(subscriptionCount) {
    console.log(`onSubscriptionSucceeded: ${subscriptionCount}`);
  }
  ```
  
  
It is this logging I am looking for

**Comment by Asim313** [comment]
got Error in onSubscriptionError:
Error: AuthError

**Comment by megabeehothanhminh** [comment]
Hello. I facing same issue 
` onAuthorizer: async (channelName, socketId): Promise<PusherAuthorizerResult> => {
          try {
            const token = await loadString(KEY_TOKEN)
            const response = await axios.post(
              Config.authEndpoint,
              {
                socket_id: socketId,
                channel_name: channelName,
              },
              {
                headers: {
                  "Content-Type": "application/json",
                  Authorization: `Bearer ${token}`,
                },
              },
            )
            return response.data
          } catch (error) {
            console.error("Failed to authenticate")
            return { auth: "" }
          }
        },`

**Comment by benw-pusher** [comment]
We've not had a response here so I'll close this. If you need further support please reach out at https://support.pusher.com/hc/en-us/requests/new

**Comment by hazhayder** [comment]
> These errors would indicate that the authentication to the channel is failing. Can you ensure you are using _either_ the authEndpoint or the onAuthorizer function? You have specified `API.postAuthData` in the onAuthorizer, howe is this defined?

This is an API endpoint which calls the broadcasting/auth endpoint of Laravel with the pusher socketID however as told earlier we aren't reaching to this point in execution. the method for Authorization is not being called altogether.
