### ISSUE TITLE
Unable to get Socket id

### ISSUE THREAD

**Issue by subhrajit-akrabhi** [pusher/pusher-websocket-react-native#92]
I have written code like this. Can you please help me out that, why I can not get socket id?
`import { Pusher } from "@pusher/pusher-websocket-react-native";
import { PUSHER_KEY, PUSHER_CLUSTER } from "@env";

export const PusherConfig = async () => {
	try {
		const pusher = Pusher.getInstance();
		await pusher.init({
			apiKey: PUSHER_KEY,
			cluster: PUSHER_CLUSTER
		});
		await pusher.connect();
		const id = await pusher.getSocketId();
		console.log("id", id);
		return pusher;
	} catch (err) {
		return err;
	}
};`

**Comment by benjamin-tang-pusher** [comment]
Hi, you've called both connect() and .getSocketId() next to eachother as asynchronous awaits, and your getSocketId() is completing faster before the connection is established, hence it will return a null.

If you put getSocketId() after the the connect() has finished, are you able to get it?

**Comment by benjamin-tang-pusher** [comment]
I will close this ticket due to lack of response.
