### ISSUE TITLE
iOS crash on 'RECONNECTING' to presence channel

### ISSUE THREAD

**Issue by raphaeldcout** [pusher/pusher-websocket-react-native#96]
### Description
I get an error when I leave the app in the background and open it again after some time using a deep_linking to a specific screen that connects to a presence channel. 
It seems that when leaving the application in the background, the 'RECONNECTING' event is called along with the subscribe presence event, generating the error, but this is just a hypothesis.

### React Native version:
React Native: 0.67.5
pusher-websocket-react-native: 1.2.2 latest

### Steps To Reproduce

1. Initialization pusher
![This is an initialization](https://drive.google.com/uc?export=view&id=1kt5YboYqiSWNmzH4bvVerrt2ohGaVs2M)

2. Import init pusher from app initialization (ignore function name)
![This is an import config init pusher](https://drive.google.com/uc?export=view&id=1av1U_MMh_V7T7LZTSosmDej19Lk6s3ke)

3. Create a screen where subscribeChannels and unsubscribeChannels
![This is a screen](https://drive.google.com/uc?export=view&id=1g7s41e79MJT7nd984OqfjDBfk4uH2BU6)

4. Connect first time on presence.channel (in my case, the app stayed in the background to open an external link to the screen that subscribeChannels and unsubscribeChannels)
![This is a first-time connection](https://drive.google.com/uc?export=view&id=1er9UYUrbVbfwsI1sPhm47I-JutuIeyRZ)

5. Connect a second time on another presence.channel (in my case, the app stayed in the background to open another external link to the screen that subscribeChannels and unsubscribeChannels)
![This is a second-time connection](https://drive.google.com/uc?export=view&id=1vyAqpf1lEkdVyeNwy8UttrCz8KITsW4z)

6. Try to connect again, and the error is displayed
![This is a connection again](https://drive.google.com/uc?export=view&id=1-rqeGx3UsUEwj0x5avYW-ryHYeHf8RXA)

7. Error:
![This is a crash error](https://drive.google.com/uc?export=view&id=1K-hQoZaYjk2Pjf-ELAES0Zcx4lot9SFd)

### More information
In my app, I have a Product screen where I need to connect and disconnect to 2 channels according to their 'id'. The first channel is common and the other is a presence channel. 
When the Product screen is mounted, the 'subscribe' event is called, when the screen is unmounted, the 'unsubscribe' event is called.
What happens in my scenario: When a Product is already connected to the channels, I leave the app in the background, and try to connect to another Product (for example deep_linking), the crash happens.

### Expected Results
No crash happen

**Comment by lluisandreu** [comment]
I can reproduce the same bug. Only in iOS.

**Comment by benjamin-tang-pusher** [comment]
Could both of you try fetching the new version of the PusherSwift library in your React Native project. There's a new version 10.1.4 that has a couple of improvements on this.
